### ISSUE TITLE
Use force layout with angular 2

### ISSUE THREAD

**Issue by orpitadutta** [tomwanzek/d3-ng2-demo#15]
How can i use force pack layout of bubble chart in wrapper with angular 4?

**Comment by tomwanzek** [comment]
For general "how to" questions related to the use of D3 in conjunction with Angular, please use StackOverflow. For one, the community is broader there for support purposes and others can not only provide guidance, but also benefit from the suggested answers. The issues for this demo should be used for bug reports or specific improvement suggestions. Thanks for understanding. :smile:
