### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by bob44240** [tomwanzek/d3-ng2-demo#9]
I don't understand some of the syntax used by the service.  For example:  
_`let d3ParentElement: Selection<HTMLElement, any, null, undefined>;`_

Is this defining Selection as a function that takes 4 parameters of the type HTMLElement, any, etc?

Can you point me to a resource describing this approach?

**Comment by tomwanzek** [comment]
@bob44240 Not a dumb question at all!!!

Your question is very valid and pertains to the new TypeScript 2 Definition files published on **DefinitelyTyped** and accessed through installed from **npm @typed**. The definitions  are relatively new, and it is only yesterday, that some Pull Requests with an outstanding chore were merged.

Namely, I added more complete JSDoc comments. While I did not get around to all modules yet in this regard, some of the key ones are covered now.

Specific to your question, if you look at [d3-selection Line 153](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/d3-selection/index.d.ts#L153), you will find an explanation of the 4 generics you were wondering about.

To get the new definitions, simply uninstall/re-install the `d3-ng2-service`:

```
npm uninstall --save d3-ng2-service
npm cache clean
npm install  --save d3-ng2-service
```

It will pull in the latest definition files. I did not have a chance to publish a patch release to indicate the newer definitions...

You will find that the JSDoc comments for methods, include an explanation of the used generics specific to them.

One of the main drivers for having the four generics on Selection is the following:
- sub-selections using `selectAll` will "promote" the previously selected group-elements to parent elements in the new sub-selection
- Parent elements and the data type defined on them can also plays a part in data joins or in sub-selection using `select`, `append` etc.

The reason, why not just the data types are used as generics on a selection is as follows. Given that D3 binds the `this` context of a value function passed e.g. into `attr(...)`, `style(...)` or `each(...), means that the new definitions will enforce the element type on`this`, based on the selection.

E.g. if you have a sub-selection of all `circle`s in an `svg`, where the datum on a circle is of type `CircleDatum` and the data on the `svg` do not matter, you would have a selection of type 

``` ts
let circles: Selection<SVGCircleElement, CircleDatum, SVGSVGElement, any>;
```

If you now invoke a callback for an attribute setter, you can access the `SVGCircleElement` as the this context:

``` ts
circles.attr('cx', function(d) {
  // bound "this" context is typed as the current SVGCircleElement for which the callback has been invoked
});
```

**Comment by tomwanzek** [comment]
Hope this helps to start you off. One comment I forgot, is that you have to be careful what the `elementRef.nativeElement` injected in Angular 2 returns. The selected element driving the first generic, depends on your specific context.

So care should be taken when casting the `nativeElement`. E.g. if you build a component that uses an attribute selector which is only permitted on an svg group element `g[foo]`, then you would expect the `elementRef.nativeElement` to be an `SVGGElement`.
